### ISSUE TITLE
This module may break soon

### ISSUE THREAD

**Issue by zeke** [sindresorhus/electron-is-dev#2]
A kind soul (@logicalparadox) has allowed us to take over the `electron` package name on npm, and we are beginning the process of publishing `electron-prebuilt` and `electron` in tandem for a while.

If a user installs the new `electron`, this package in its current form will not be able to detect that, because it's looking for `-prebuilt` in the path name:

``` js
module.exports = process.defaultApp || /[\\/]electron-prebuilt[\\/]/.test(process.execPath);
```

Context: https://github.com/electron-userland/electron-prebuilt/issues/160

**Comment by parro-it** [comment]
Thank you for the notice @zeke. We was planning to change the check and use an env variable.
We are discussing it [here](#1) and [here](https://github.com/electron-userland/electron-prebuilt/issues/116)

I did a [PR on electron-prebuilt](https://github.com/electron-userland/electron-prebuilt/pull/118) to make it set such variable, so that we can check it. 

This should solve the name change problem.

**Comment by zeke** [comment]
cc @kevinsawicki who suggested there might be a baked-in way to do this already.
